set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER "${MINGW_TOOLCHAIN_ROOT}/bin/${MINGW_COMPILER}-gcc")
set(CMAKE_CXX_COMPILER "${MINGW_TOOLCHAIN_ROOT}/bin/${MINGW_COMPILER}-g++")
set(CMAKE_RC_COMPILER "${MINGW_TOOLCHAIN_ROOT}/bin/${MINGW_COMPILER}-windres")
set(CMAKE_AR "${MINGW_TOOLCHAIN_ROOT}/bin/${MINGW_COMPILER}-ar")
set(CMAKE_RANLIB "${MINGW_TOOLCHAIN_ROOT}/bin/${MINGW_COMPILER}-ranlib")

# Third-party static libs (opt/lib/...) plus the toolchain's own mingw sysroot.
set(CMAKE_FIND_ROOT_PATH
    "${CMAKE_PREFIX_PATH}"
    "${MINGW_TOOLCHAIN_ROOT}/${MINGW_COMPILER}"
    )
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
